10 add a user account page
bl1231/bilbomd-ui pull request #620
Opened 2024-08-21 22:36 UTC by shrprabh

feat: Implement user account management with email update, OTP verification, and account deletion

- Added `UserAccount` component to manage user information, including username, email, and roles.
- Implemented the ability to update the user's email address with OTP verification:
  - User can request an OTP to be sent to the new email address.
  - User can verify the OTP to confirm the email change.
  - Added automatic logout after successful email change.
- Added a feature to resend the OTP if the user didn't receive it.
- Integrated a delete account feature with confirmation dialog:
  - User is prompted with a confirmation dialog before account deletion.
  - If confirmed, the account is deleted via an API call.
- Integrated MUI components (`Card`, `Typography`, `TextField`, `Button`, etc.) for a responsive and accessible UI.
- Used `react-toastify` for providing feedback to users with success and error messages.
- Used `useAuth` and `useLogout` hooks to manage authentication and logout functionality.
- Ensured proper state management using `useState` hooks for handling inputs, modals, and confirmation visibility.

2024-10-14 18:53 UTC, dsclassen requested changes
Fix these small items and I will merge

2024-10-14 18:53 UTC, dsclassen commented on src/features/users/UserAccount.tsx
> +        showMessageDialog('Email address already exists')
Should be:

"This Email is already associated with another account"

2024-10-14 18:53 UTC, dsclassen commented on src/features/users/UserAccount.tsx
> +    console.log('Verifying OTP:', values.otp)
Please comment out so console logs don't appear in production deployment.

2024-10-14 18:53 UTC, dsclassen commented on src/features/users/UserAccount.tsx
> +      console.log('Updating email to:', values.newEmail)
Please comment out so console logs don't appear in production deployment.

2024-10-14 18:53 UTC, dsclassen commented on src/features/users/UserAccount.tsx
> +      console.log('Deleting account:', username)
Please comment out so console logs don't appear in production deployment.

2024-10-14 18:53 UTC, dsclassen commented on src/slices/usersApiSlice.ts
Please revert this change. Your feature does not need to edit this file. Keep your PR clean

2024-10-14 19:16 UTC, dsclassen commented
In the rare cases when either the new email address has a typo or for some reason can't be delivered I think it would be good to perhaps add a little "X" to the OTP entry dialog box so it can be dismissed.

2024-10-15 00:16 UTC, shrprabh commented on src/features/users/UserAccount.tsx
> +        showMessageDialog('Email address already exists')
Done

2024-10-15 00:16 UTC, shrprabh commented on src/features/users/UserAccount.tsx
> +    console.log('Verifying OTP:', values.otp)
Done

2024-10-15 00:16 UTC, shrprabh commented on src/features/users/UserAccount.tsx
> +      console.log('Updating email to:', values.newEmail)
Done

2024-10-15 00:16 UTC, shrprabh commented on src/slices/usersApiSlice.ts
Done

2024-10-15 16:17 UTC, dsclassen approved these changes

2024-10-15 16:17 UTC, merged